name = "npsp-ai-search"
main = "worker.js"
compatibility_date = "2024-12-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CACHE"
id = "b36b0f495c5b4faab3863a19ddd7d53d"

[vars]
ALLOWED_ORIGINS = "https://epugach.github.io,http://localhost:8000,http://localhost:3000"
SHEETS_LOG_URL = "https://script.google.com/macros/s/AKfycbznRfuyxM8TnpEtEkA8_GeeqBRUK8t7QZbrLDSwD3bbV4Wrjl08aykn0ThJoOqLIUCBwg/exec"
